apiVersion: v1
kind: Service
metadata:
  name: test-app-orginal
  labels:
    app: test-app-orginal
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-orginal
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-orginal
  name: test-app-orginal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-orginal
  template:
    metadata:
      labels:
        app: test-app-orginal
    spec:
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: IfNotPresent
        name: test-app
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: postgresql://test-summon-sidecar-app-backend.{{ TEST_APP_NAMESPACE_NAME }}.svc.cluster.local:5432/postgres
          - name: DB_USERNAME
            value: test_app
          - name: DB_PASSWORD
            value: 5b3e5f75cb3cdc725fe40318

