---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 # TODO: change this to match your k8s version
metadata:
  name: conjur-authenticator-role-binding
  namespace: orquestador
subjects:
  - kind: ServiceAccount
    name: conjur-oss
    namespace: conjur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-oss-conjur-authenticator
